version: "3.8"

services:
  db:
    image: postgres:14
    container_name: tienda_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tienda_db
    volumes:
      - ./data/db:/var/lib/postgresql/data # Volumen para persistir los datos
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql # Crear tablas
      - ./migrations/seed.sql:/docker-entrypoint-initdb.d/seed.sql # Insertar datos
    ports:
      - "5432:5432" # Puerto de PostgreSQL
    networks:
      - tienda_network

  backend:
    build: ./backend
    container_name: tienda_backend
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: password
      DB_NAME: tienda_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - tienda_network

  frontend:
    build: ./frontend
    container_name: tienda_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tienda_network

networks:
  tienda_network:
    driver: bridge
